services:
  notification-adapter-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: notification-adapter-api
    restart: always
    ports:
      - "8081:8081"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
