services:
  notification-adapter-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: notification-adapter-api
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true